### PR TITLE
Visualization cytoscape

### PR DESCRIPTION
**Pull request by ortega2247**
this is the visualization class of PySB models. To run the models it is necessary to have cytoscape open

### CODE REVIEW

**Comment by JamesPino** [comment]
There are some files that depend on earm being installed. Maybe you can use the earm from examples?

Also there is a place where you set parameters from your local directory path. Will default parameters work?

**Comment by ortega2247** [comment]
@JamesPino Thanks for the comments.  I changed the code to use earm1.0 and the default parameters. What do you mean that i need to helper_functions to path?

**Comment by JamesPino** [comment]
I thought the previous travis test showed that it failed because there wasn't a module 'helper_functions'. You might have already changed it to pysb.tools.helper_functions. I can't seem to find the error in the output anymore.

I do see that it failed with no module PIL. 
`  File "/home/travis/build/LoLab-VU/pysb/build/lib/pysb/tools/model_visualization.py", line 15, in <module>
    from PIL import ImageFont
ImportError: No module named PIL
`

I'll keep looking. Maybe that was something else

**Comment by ortega2247** [comment]
You were right. I already fixed the PIL ImportErro, the error that throws now is related to cytoscape, as it needs to be open to run the code. I think @alubbock said that it is not possible to get rid of that error because there is no a headles cytoscape. However, i found this version: https://github.com/cytoscape/cytoscape-headless-distribution should i try to use it?

**Comment by JamesPino** [comment]
It looks like it isn't being developed any more. I wonder if turning of tests for that in Travis is the short term solution? Since it is specific for a tool.

**Pull request closed without merging**
